
const menuToggle=document.querySelector('.menu-toggle'),mainNav=document.querySelector('.main-nav');
if(menuToggle&&mainNav){
    const setMenuState=open=>{
        mainNav.classList.toggle('open',open);
        menuToggle.setAttribute('aria-expanded',String(open));
        menuToggle.setAttribute('aria-label',open?'Close navigation menu':'Open navigation menu');
    };
    menuToggle.addEventListener('click',()=>setMenuState(!mainNav.classList.contains('open')));
    mainNav.addEventListener('click',event=>{if(event.target.closest('a'))setMenuState(false)});
    document.addEventListener('keydown',event=>{if(event.key==='Escape')setMenuState(false)});
}
const galleryImages=Array.from(document.querySelectorAll('.gallery figure img'));const lightbox=document.getElementById('lightbox');
if(lightbox&&galleryImages.length){const lightboxImg=lightbox.querySelector('img'),caption=lightbox.querySelector('p')||document.createElement('p'),closeBtn=lightbox.querySelector('.lightbox-close');if(!caption.parentNode)lightbox.appendChild(caption);lightbox.setAttribute('role','dialog');lightbox.setAttribute('aria-modal','true');lightbox.setAttribute('aria-label','Photo viewer');let activeIndex=0,lastFocused=null;const prev=document.createElement('button');prev.className='lightbox-nav lightbox-prev';prev.textContent='‹';prev.type='button';prev.setAttribute('aria-label','Previous photo');const next=document.createElement('button');next.className='lightbox-nav lightbox-next';next.textContent='›';next.type='button';next.setAttribute('aria-label','Next photo');lightbox.append(prev,next);function openLb(i){activeIndex=i;lastFocused=document.activeElement;const img=galleryImages[i];lightboxImg.src=img.currentSrc||img.src;lightboxImg.alt=img.alt;caption.textContent=img.closest('figure').querySelector('figcaption')?.textContent||img.alt;lightbox.classList.add('open');document.body.classList.add('lightbox-active');closeBtn.focus()}function closeLb(){lightbox.classList.remove('open');document.body.classList.remove('lightbox-active');lightboxImg.src='';lastFocused?.focus()}function move(d){openLb((activeIndex+d+galleryImages.length)%galleryImages.length)}galleryImages.forEach((img,i)=>{const figure=img.closest('figure');img.addEventListener('click',()=>openLb(i));figure?.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openLb(i)}})});closeBtn.addEventListener('click',closeLb);prev.addEventListener('click',e=>{e.stopPropagation();move(-1)});next.addEventListener('click',e=>{e.stopPropagation();move(1)});lightbox.addEventListener('click',e=>{if(e.target===lightbox)closeLb()});document.addEventListener('keydown',e=>{if(!lightbox.classList.contains('open'))return;if(e.key==='Escape')closeLb();if(e.key==='ArrowLeft')move(-1);if(e.key==='ArrowRight')move(1)})}
const form=document.getElementById('enquiryForm');if(form)form.addEventListener('submit',e=>{e.preventDefault();const name=document.getElementById('enqName').value.trim(),course=document.getElementById('enqCourse').value.trim(),date=document.getElementById('enqDate').value.trim(),students=document.getElementById('enqStudents').value.trim();const msg=`Hi, I am interested in Ashok Boys Hostel near SASTRA SRC Campus.\nName: ${name||'-'}\nCourse / Year: ${course||'-'}\nExpected joining date: ${date||'-'}\nNumber of students: ${students||'-'}\nPlease share room availability.`;window.open(`https://wa.me/919443665708?text=${encodeURIComponent(msg)}`,'_blank')});
